= Graph
:toc:
:icons:
:data-uri:
:author: Christoph Dittmann
:email: github@christoph-d.de
:source-highlighter: pygments
:language: typescript

== Graph

.Create a simple graph
[source]
g = new G.Graph<Vertex, Edge>({ numVertices: 4, edgeList: [[0,1], [1,2]] });

If you need more than a plain graph, then instead of `G.Graph` you may
want to use `G.graphFromJSON()` or specific subclasses such as
`G.ParityGame`.

=== General Concepts

Every `Graph` method that works on existing vertices expects an
argument of type `VertexDescriptor`.  A `VertexDescriptor` is simply
an object with one required property called `id: number` identifying a
vertex.  Every `Vertex` object in the graph has this property, so it
is compatible to `VertexDescriptor`.

Similarly, methods working on existing edges expect a `EdgeDescriptor`
object, which contains two mandatory fields `head: number` and `tail:
number`, identifying the endpoints of an edge.  Because we work with
simple graphs, the endpoints uniquely identify an edge.

Internally, edges also have ids.  However, `Graph` offers no methods
to work with these ids, so you must use `EdgeDescriptor` objects.

Note that `VertexDescriptor` and `EdgeDescriptor` objects may have
many more fields.  These will be passed on to the Vertex or Edge
constructor whenever possible.

=== Graph Methods

Graph<V,E>::addVertex(vertexArguments?: any): V:: Adds a new vertex to
the graph.  The `vertexArguments` are passed on to the `V`
constructor.  Dispatches the event `postAddVertex` to the graph with
the new `V` object as an argument.  Returns the new vertex.

Graph<V,E>::findVertex(v: VertexDescriptor): V:: Returns the vertex
identified by `v`.  Throws an error if such a vertex does not exist.

Graph<V,E>::hasVertex(v: VertexDescriptor): boolean:: Return `true` if
`v` identifies an existing vertex.

Graph<V,E>::removeVertex(v: VertexDescriptor):: Removes the vertex
identified by `v`.  Precondition: `v` must be an element of
`Graph<V,E>::getVertices()`.  You may want to call
`Graph<V,E>::compressIds()` afterwards to remove `null` entries from
the vertex list.  Dispatches the event `postRemoveVertex` to the
graph.

Graph<V,E>::addEdge(e: EdgeDescriptor): E:: Adds a new edge to the
graph.  Dispatches the event `postAddEdge` to the graph with the new
`E` object as an argument.  Throws an error if head/tail on `e` are
missing or invalid.  Returns the new edge.

Graph<V,E>::findEdge(e: EdgeDescriptor): E:: Returns the edge
identified by `e`.  Throws an error if such an edge does not exist.

Graph<V,E>::hasEdge(e: EdgeDescriptor): boolean:: Return `true` if `e`
identifies an existing edge.

Graph<V,E>::removeEdge(e: EdgeDescriptor):: Removes the edge
identified by `e`.  Dispatches the event `postRemoveEdge` to the
graph.

Graph<V,E>::compressIds():: Reassigns all vertex and edge ids in order
to remove `null` entries from the internal list of vertices and the
internal list of edges.

Graph<V,E>::getVertices(): V[]:: Returns the list of vertices without
`null` entries.
Graph<V,E>::getVertices(vertexFilter): V[]:: Like
`Graph<V,E>::getVertices()`, but returns only vertices `v` where
`vertexFilter(v)` returns `true`.

Graph<V,E>::getEdges(): E[]::
Graph<V,E>::getEdges(edgeFilter): E[]:: Like
`Graph<V,E>::getVertices()`, but for edges.

Graph<V,E>::vertices: (V | null)[]:: The internal list of vertices.
May contain `null` entries.  `tail`/`head` of the edges refer to
indices in this array.  If a vertex with id `i` exists, then it will
be in position `i` in the array `Graph<V,E>::vertices`.
Graph<V,E>::edges: (E | null)[]:: The internal list of edges.  May
contain `null` entries.  The order of the edges is unspecified.

=== Helper Methods

graphjson.graphFromJSON(json):: Creates a graph from the specified string,
parsing it as JSON.  Can create `G.ParityGame` or other (whitelisted)
graphs, depending on the JSON content.

== Events

`Graph`, `Vertex` and `Edge` all derive from `Listenable` which
enables event handling.  You can fire events by calling
`x.dispatch("eventname"[, arg1, arg2, ...])` on some instance `x`.

You can register a one-shot listener function with with
`x.on("eventname", somefunction, { once: true })`.  Then
`someFunction` will be called whenever `"eventname"` is dispatched.
The `this` context of `someFunction` will be `x` and `someFunction`
will receive the arguments provided to `dispatch`.

You can also register permanent listeners with `x.on("eventname",
someFunction)`.  You can remove all listeners with
`x.removeListeners("eventname")`.

You can also register listeners directly on a class instead of an
instance with `ClassName.onStatic("eventname", someFunction)`.  This
is only recommended for listeners that are added immediately after the
class definition.  This is because subclasses copy the static
listeners of their base class at the first opportunity, so listeners
added to the base class later will not be able to listen to events on
the subclass.

=== Predefined Events

Some events are predefined.

The event `"changeGraphStructure"` is fired on a graph whenever the
structure of the graph changes in a way that might affect the result
of graph algorithms.

In particular, `"changeGraphStructure"` fires when adding/removing
vertices/edges and when changing most vertex/edge properties, for
example when changing the priority of a vertex in a parity game.  One
notable exception is that changing the x/y coordinates of a vertex
does not fire this event.

The following events are automatically followed by a
`"changeGraphStructure"` event:

 - `"postAddVertex"`, `"postRemoveVertex"`: Called after
   adding/removing a vertex.  Receive the vertex as an argument.
 - `"postAddEdge"`, `"postRemoveEdge"`: Called after adding/removing
   an edge.  Receive the edge as an argument.

The `"changeGraphStructure"` event is automatically followed by a
`"redrawNeeded"` event, which queues a redraw request for the whole
graph.  Changing the x/y coordinates of a vertex automatically fires
`"redrawNeeded"`, too.

Both `"changeGraphStructure"` and `"redrawNeeded"` can be fired
manually by calling `dispatch` on a `Graph` instance.  If all you have
is a vertex or an edge, you can call
`VertexOrEdge::"changeGraphStructure"` to fire
`changeGraphStructure` or `VertexOrEdge::queueRedraw` to fire
`"redrawNeeded"`.

.Example
[source]
g = new G.Graph<Vertex, Edge>({ numVertices: 4, edgeList: [[0,1], [1,2]] });
g.on("postAddVertex", (v) => console.log(`Added vertex ${v.id}!`));
g.addVertex() // Prints "Added vertex 4!";
